name: Build Android (Unity)

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-Android-${{ hashFiles('**/Packages/packages-lock.json') }}
          restore-keys: |
            Library-Android-

      - name: Build (GameCI)
        uses: game-ci/unity-builder@v4
        with:
          targetPlatform: Android
          # unityVersion: 2022.3.##   # при желании зафиксируй LTS
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

      - name: Upload Editor Log
        uses: actions/upload-artifact@v4
        with:
          name: EditorLog
          path: ~/.local/share/unity3d/Editor.log

      - name: Upload Android Build
        uses: actions/upload-artifact@v4
        with:
          name: AndroidBuild
          path: build/Android