name: Apply file blocks from issue to main

on:
  issue_comment:
    types: [created]
  issues:
    types: [edited]

permissions:
  contents: write
  issues: read

jobs:
  apply:
    if: |
      github.event_name == 'issue_comment' ||
      github.event_name == 'issues'
    runs-on: ubuntu-latest
    env:
      OWNER: ${{ github.repository_owner }}
      REPO: ${{ github.event.repository.name }}
      PAT: ${{ secrets.WORKFLOW_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract code blocks from issue
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const body = context.payload.comment?.body || context.payload.issue?.body || '';
            const regex = /file:(.*?)\n+```[\s\S]*?```/g;
            let match;
            let idx = 1;
            while ((match = regex.exec(body)) !== null) {
              const path = match[1].trim();
              const content = match[0].replace(/^file:.*?\n+```/, '').replace(/```$/, '');
              fs.writeFileSync(`path${idx}.txt`, path);
              fs.writeFileSync(`data${idx}.txt`, content);
              idx++;
            }

      - name: Apply changes
        run: |
          set -euo pipefail
          if [[ -z "${PAT:-}" ]]; then
            echo "WORKFLOW_TOKEN not set; skipping .github/workflows/* updates."
            exit 0
          fi
          
          git config user.name  "agent-bot"
          git config user.email "agent@users.noreply.github.com"
          git remote set-url origin "https://x-access-token:${PAT}@github.com/${OWNER}/${REPO}.git"
          
          changed=0
          for p in path*.txt; do
            idx=${p##path}; idx=${idx%%.txt}
            path=$(sed 's/\r$//' "path${idx}.txt")
            if [[ "$path" == .github/workflows/* ]]; then
              mkdir -p "$(dirname "$path")"
              cp "data${idx}.txt" "$path"
              echo "Wrote workflow $path"
              git add "$path"
              changed=1
            fi
          done
          
          if [[ "$changed" -eq 1 ]]; then
            git commit -m "chore(agent): apply workflow files from issue"
            git push origin HEAD:main
          else
            echo "No workflow files found to push with PAT."
          fi
