name: Apply file blocks from Issue -> MAIN

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  apply:
    runs-on: ubuntu-latest
    env:
      OWNER: ${{ github.repository_owner }}
      REPO:  ${{ github.event.repository.name }}
      PAT:   ${{ secrets.WORKFLOW_TOKEN }}
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Extract file blocks (python)
        id: extract
        shell: bash
        run: |
          set -euo pipefail
          BODY="$(jq -r '.comment.body // .issue.body // ""' "$GITHUB_EVENT_PATH")"
          printf '%s\n' "$BODY" > body.txt
          python3 - << 'PY'
import re, pathlib
body = pathlib.Path("body.txt").read_text(encoding="utf-8", errors="ignore")
# Нормализуем \r\n -> \n
body = body.replace("\r\n", "\n")
# Ищем блоки ```file:... \n ... \n```
pattern = re.compile(r"```file:\s*([^\n]+)\n(.*?)```", re.DOTALL)
matches = list(pattern.finditer(body))
for i, m in enumerate(matches, start=1):
    path = m.group(1).strip()
    data = m.group(2)
    pathlib.Path(f"path{i:03}.txt").write_text(path, encoding="utf-8")
    pathlib.Path(f"data{i:03}.txt").write_text(data, encoding="utf-8")
print(f"FOUND_BLOCKS={len(matches)}")
PY
          # экспортируем число найденных блоков в outputs
          FOUND=$(grep -oE 'FOUND_BLOCKS=[0-9]+' <<< "$(tail -n 1 ./-)" || true)
          # Если по какой-то причине grep не нашёл, посчитаем по файлам
          if [ -z "${FOUND}" ]; then
            COUNT=$(ls -1 path*.txt 2>/dev/null | wc -l | tr -d ' ')
          else
            COUNT=${FOUND#FOUND_BLOCKS=}
          fi
          echo "found=${COUNT:-0}" >> "$GITHUB_OUTPUT"
          echo "Found ${COUNT:-0} file block(s)."
          if [ "${COUNT:-0}" = "0" ]; then
            echo "No file blocks found. Add a comment with:"
            echo '```file:.github/workflows/your.yml'
            echo '<file content>'
            echo '```'
            exit 0
          fi

      - name: Apply non-workflow files (via GITHUB_TOKEN)
        if: steps.extract.outputs.found != '0'
        shell: bash
        run: |
          set -euo pipefail
          git config user.name  "agent-bot"
          git config user.email "agent@users.noreply.github.com"

          changed=0
          for p in path*.txt; do
            i=${p##path}; i=${i%%.txt}
            path=$(cat "path${i}.txt")
            case "$path" in
              .github/workflows/*) continue ;;
            esac
            mkdir -p "$(dirname "$path")"
            cp "data${i}.txt" "$path"
            echo "Wrote $path"
            git add "$path"
            changed=1
          done

          if [ "$changed" = "1" ]; then
            git commit -m "chore(agent): apply non-workflow files from issue"
            git push origin HEAD:main
          else
            echo "No non-workflow files to push."
          fi

      - name: Apply workflow files (requires PAT with workflow scope)
        if: steps.extract.outputs.found != '0'
        shell: bash
        run: |
          set -euo pipefail
          if [ -z "${PAT:-}" ]; then
            echo "WORKFLOW_TOKEN not set; skipping workflow updates."
            exit 0
          fi

          git config user.name  "agent-bot"
          git config user.email "agent@users.noreply.github.com"

          changed=0
          for p in path*.txt; do
            i=${p##path}; i=${i%%.txt}
            path=$(cat "path${i}.txt")
            case "$path" in
              .github/workflows/*)
                mkdir -p "$(dirname "$path")"
                cp "data${i}.txt" "$path"
                echo "Wrote workflow file: $path"
                git add "$path"
                changed=1
                ;;
            esac
          done

          if [ "$changed" = "1" ]; then
            git commit -m "chore(agent): apply workflow files from issue"
            # пушим по URL с PAT, чтобы были права на workflows
            git push "https://x-access-token:${PAT}@github.com/${OWNER}/${REPO}.git" HEAD:main
          else
            echo "No workflow files to push with PAT."
          fi