name: Apply file blocks from Issue -> MAIN

on:
  issues:
    types: [opened, edited, labeled]
  issue_comment:
    types: [created]

permissions:
  contents: write

jobs:
  apply-to-main:
    if: >
      (github.event_name == 'issues' && contains(github.event.issue.title, '[PATCH:MAIN]')) ||
      (github.event_name == 'issues' && github.event.action == 'labeled' && github.event.label.name == 'apply-to-main') ||
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '```'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Extract code blocks
        id: extract
        shell: bash
        run: |
          set -euo pipefail
          BODY=$(jq -r '.comment.body // .issue.body' "$GITHUB_EVENT_PATH")
          printf '%s\n' "$BODY" > body.txt

          # Вытащим все код-блоки """file:PATH ... """
          # Каждый блок сохраняем во временный файл: path<idx>.txt и data<idx>.txt
          awk '
            BEGIN {inb=0; idx=0}
            /^```/ {
              if (!inb) {
                line=$0
                if (match(line, /^```file:([^\r\n]+)$/, m)) {
                  inb=1; path=m[1]; idx++; printf "%s\n", path > sprintf("path%03d.txt", idx); next
                } else {
                  next
                }
              } else { inb=0; next }
            }
            { if (inb) print > sprintf("data%03d.txt", idx) }
          ' body.txt

          count=$(ls -1 data*.txt 2>/dev/null | wc -l | tr -d " ")
          echo "found=$count" >> $GITHUB_OUTPUT
          echo "Found $count file-block(s)."

          if [ "$count" = "0" ]; then
            echo "No ```file:PATH code blocks found. Please wrap content like:"
            echo '```file:.github/workflows/my.yml'
            echo '<file content here>'
            echo '```'
            exit 1
          fi

      - name: Apply files and push
        if: steps.extract.outputs.found != '0'
        shell: bash
        run: |
          set -euo pipefail
          git config user.name  "agent-bot"
          git config user.email "agent@users.noreply.github.com"

          for p in path*.txt; do
            idx=${p##path}; idx=${idx%%.txt}
            path=$(cat "path${idx}.txt")
            mkdir -p "$(dirname "$path")"
            cp "data${idx}.txt" "$path"
            echo "Wrote $path"
            git add "$path"
          done

          git commit -m "chore(agent): apply file blocks from issue #${GITHUB_EVENT_NUMBER:-manual}"
          git push origin HEAD:main