name: Apply file blocks from Issue -> MAIN

on:
  issues:
    types: [opened, edited, labeled]
  issue_comment:
    types: [created]

permissions:
  contents: write
  workflows: write   # <— ВАЖНО: даём право создавать/обновлять workflow-файлы

jobs:
  apply-to-main:
    if: >
      (github.event_name == 'issues' && contains(github.event.issue.title, '[PATCH:MAIN]')) ||
      (github.event_name == 'issues' && github.event.action == 'labeled' && github.event.label.name == 'apply-to-main') ||
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '```file:'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Extract code blocks
        id: extract
        shell: bash
        run: |
          set -euo pipefail
          BODY=$(jq -r '.comment.body // .issue.body' "$GITHUB_EVENT_PATH")
          printf '%s\n' "$BODY" > body.txt

          # Вытаскиваем блоки формата: ```file:PATH \n <контент> \n ```
          awk '
            BEGIN {inb=0; idx=0}
            /^```/ {
              if (!inb) {
                if (match($0, /^```file:([^\r\n]+)$/, m)) {
                  inb=1; path=m[1]; idx++; printf "%s\n", path > sprintf("path%03d.txt", idx); next
                } else { next }
              } else { inb=0; next }
            }
            { if (inb) print > sprintf("data%03d.txt", idx) }
          ' body.txt

          count=$(ls -1 data*.txt 2>/dev/null | wc -l | tr -d " ")
          echo "found=$count" >> $GITHUB_OUTPUT
          [ "$count" != "0" ]

      - name: Apply & push to main
        if: steps.extract.outputs.found != '0'
        shell: bash
        run: |
          set -euo pipefail
          git config user.name  "agent-bot"
          git config user.email "agent@users.noreply.github.com"

          for p in path*.txt; do
            idx=${p##path}; idx=${idx%%.txt}
            path=$(sed 's/\r$//' "path${idx}.txt") # срежем CR если вставили из Windows
            mkdir -p "$(dirname "$path")"
            cp "data${idx}.txt" "$path"
            echo "Wrote $path"
            git add "$path"
          done

          git commit -m "chore(agent): apply file blocks from issue #${GITHUB_EVENT_NUMBER:-manual}"
          git push origin HEAD:main