name: Unity Tests (EditMode + PlayMode)

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-Tests-${{ hashFiles('**/Packages/packages-lock.json') }}
          restore-keys: |
            Library-Tests-

      - name: Run Unity Tests
        uses: game-ci/unity-test-runner@v4
        with:
          testMode: all            # editmode + playmode
          # unityVersion: 2022.3.## # опционально закрепи свою LTS
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          # Если активации по одному UNITY_LICENSE окажется мало,
          # добавь ещё:
          UNITY_EMAIL:    ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: |
            artifacts
            **/TestResults.xml